### ISSUE TITLE
 I lost my account

### ISSUE THREAD

**Issue by viviOwO** [howlrapp/howlr-app#12]
Hello, so i have little problem, after I formated my cellphone, when i loged in my account with the same account in telegram, your app create a new account to me, so... How can i get back my account? My name profile is "Nalu" in the 2 accounts.

**Comment by yiffboy16** [comment]
This stupid app has zero support. I'm gonna guess you are just screwed over. They build an app, but just ignore the people using it.

**Comment by Dax911** [comment]
> This stupid app has zero support. I'm gonna guess you are just screwed over. They build an app, but just ignore the people using it.

Excuse fucking me.  This is an open source app built for the community as a practice project. You are lucky that they have been eating the cost for hosting this app for years.  Do not just sign up for GitHub to complain about a developer.  This is highly inappropriate and very unprofessional.  If you want a change within the app opening a ticket is fine and the code base is right here if you want to fork it and do it yourself.  That is the nature of open source and why they published it. So that other people can contribute and add to the features and changes.  Be part of the solution not the problem.  

There is no money being made by the developers so unless you want ads or a paywall there is no reason or incentive to offer support and even if they did why would they want to help such an entitled pompous ass as yourself.  They are loosing money with this app so I am sure you can find some engineers who will give you customer support if you pay them. 

Good luck to you and have a nice night. Please get the fuck out and off GitHub.

**Comment by yiffboy16** [comment]
Just because they share half the source or host it, doesn't mean they're free from criticism. Yes, my comment is a little salty, because consistently the experience with Howler for me and people I know has been far below great. And yes, they 'pay' for the servers, although that seems to also be funded in great part from the community. They say it costs ~$95 USD a month, Patreon covers $80 of that.
So, I don't think it's outrageous to at least have a community moderation system, given there is _zero_ ways to appeal anything, to get in contact with anyone who can actually help the users of the platform, etc. 

I do appreciate the effort they made in making the app, but that doesn't mean I'm not going to judge the app in the same way I would any other. It's a blatant disservice to the users and community to go completely radio silent, and have zero ways of users getting help.

**Comment by Dax911** [comment]
> Just because they share half the source or host it, doesn't mean they're free from criticism. Yes, my comment is a little salty, because consistently the experience with Howler for me and people I know has been far below great. And yes, they 'pay' for the servers, although that seems to also be funded in great part from the community. They say it costs ~$95 USD a month, Patreon covers $80 of that.
> 
> So, I don't think it's outrageous to at least have a community moderation system, given there is _zero_ ways to appeal anything, to get in contact with anyone who can actually help the users of the platform, etc. 
> 
> 
> 
> I do appreciate the effort they made in making the app, but that doesn't mean I'm not going to judge the app in the same way I would any other. It's a blatant disservice to the users and community to go completely radio silent, and have zero ways of users getting help.

I don't have an issue with that. I have an issue with the fact that you created an account and your only contributions are on this repository to complain. This is a professional space where developers share their work. It's tantamount to you going into this developers place of work to complain about a gift that they spend $200 USD a month on in-front of everybody. You don't even know how to convert currency or backup what you are saying. If you really want support you should use a platform that is meant for that like Patreon. Donate some money and use the DM functionality there. At least then it might be worthwhile for them to listen to your sniveling. ￼Howlr was never supposed to be perfect. It was a practice project. And for a practice project it's fantastic. 

At the end of the day my issue is not with the fact that you raised concerns, they are valid concerns, my issue is where and how you chose to raise them. Your behavior is exactly why countless developers like myself have to distance ourselves from our users. And why it's so hard to create apps for free for everyone. Your demands on our time become a black hole not only sucking in time and money but bringing down our morale as well. I have already issued a complaint against you with Github and hope to see your account deleted soon. 

Best of luck and you are always welcome back when you are a professional software engineer ready to contribute to solutions rather than cause problems.

**Comment by yiffboy16** [comment]
The only reason this is a new account, is because I prefer to keep my furry life away from my professional life. However after the experience I had with their application, I wasn't going to be fucked over and not say anything about it. I wouldn't have an issue with these issues within the app, if the developers actually made even a pretend effort to communicate with their community. I have worked on Open Source projects, and actually communicating has always been the biggest thing.

But after being falsely banned, I tried every channel I could think of to talk to anyone who could help me. I wasn't even upset at the time, I just wanted to get my account back. My frustration mounted when there was absolutely ZERO ways to actually talk to anybody. The only channel I found was to post here, on GitHub. 

That's why I posted here, they leave zero avenues to communicate to them otherwise. So either I have no methods of dealing with issues, or I have to **_PAY_** to try and **hope** I can find any help with __them falsely banning me__. How does that not sound like absolute bullshit?

I would be so much more understanding and empathetic if they even seemed to make the slightest effort to work with the community. Or hell, if they made it so we could fork the server and fix issues we see ourselves (as they said they would). Even their website seems like they haven't bothered updating for years now at this point. 

I understand that this isn't the time nor place for venting frustrations to the developers, **but where the fuck would I got elsewhere**, they leave us no other options. That's what I'm pissed off about more than anything else. That they don't put even the smallest effort to pretend like they want to work with their community.

**Comment by howlrapp** [comment]
Hello @viviOwO !

That's because you used a different Telegram account from the one you previously used to create your Howlr account. There's no solution for this problem at the moment sadly. Please report your old account on the app and we will deactivate it.
