### ISSUE TITLE
Server Source Code

### ISSUE THREAD

**Issue by yiffboy16** [howlrapp/howlr-app#13]
Will the server source be made available at any time soon? Like, maybe allow people who are actually going to put an effort into the app and community can make Howlr, ya know, not be terrible. Oh, and importantly, maybe they can make a fork that has *some* sort of community support, but hey, having complete radio silence works too.

**Comment by Dax911** [comment]
They clearly have other things on their plate and releasing the backend code would significantly increase their security risks in the short term requiring their full attention and long term full time project management.  It is obviously not something they are ready to do.  The front end code is right there and AWS has a free tier there is nothing stopping you from writing your own clone.

**Comment by yiffboy16** [comment]
I would believe that, but it doesn't seem anything about this has been updated in a long while. They went radio silent in about 2018, the app still looks like it was build forever ago, there is no means of support, the last commit was close to a year ago at this point. It just seems like the project is being neglected, and on their site (which was updated god knows when) they said they are going to release the server source ... I just wonder if GTA 6 will release before they actually release it.

**Comment by howlrapp** [comment]
Hello @yiffboy16 !

We are still planning on releasing it, not sure when though. Here are the steps we want to follow: 
* cleanup the code (it's really small, but it lacks comments) and make the server easily installable on a development environment
* write an installation and deployment guide
* have some kind of closed preview if anyone wants to look for security issues before we release it, our unit tests covers most logical errors we could think of and we try to follow the best practices as well as we can, but you never know.

I'll close this issue when the backend part is released.

**Comment by howlrapp** [comment]
- [x] Cleanup the legacy stuff
- [x] Write a README in English (it's currently in French) with installation instructions (in progress)
- [x] Publish our reverse-geocoding server code (it can be done before we release the backend)
- [x] Write a better seed script so that people don't have to manually add every groups, genders, etc
- [x] Push the code coverage to 100% (it's currently at 99.87)
- [x] Add sample config and credentials files (in progress)
- [x] Move from encrypted credentials files to environment variables (I think it's easier to do it that way for open source projects) (in progress)
- [x] Find a simple way to set a special user for Apple reviewer (our current method is not scalable for multiple apps)
- [x] Look into that https://github.com/howlrapp/howlr-app/issues/53
