### ISSUE TITLE
Like button doesn't work 

### ISSUE THREAD

**Issue by mahogato** [howlrapp/howlr-app#15]
Almost always when i click like button on someone else's profile, it doesn't set as liked

**Comment by howlrapp** [comment]
Hello there and thanks for your report! It is a duplicate of this issue https://github.com/howlrapp/howlr-app/issues/3 and it should hopefully be fixed in the next release. I say "hopefully" because we really have a hard time reproducing this issue, however we found an obvious mistake that could lead to that kind of behaviour, and fixed it.
