### ISSUE TITLE
Feature Request: Group Chat

### ISSUE THREAD

**Issue by Endobear** [howlrapp/howlr-app#43]
I think an option for a group chat would be great because of how there is so many groups so you can chat with people that have the same interests than you.  Or you can create your own group chat with selected people.

**Comment by howlrapp** [comment]
Hello! That something we have in mind for quite a long time now, but it's impracticable or not desirable for us in a few ways:
- Groups must be moderated, and moderation is hard, it would need dozens of moderators across all groups as well as people managing those moderators, it is not practical for us
- The chat on Howlr is only there so people can talk for a bit and switch to another platform (usually Telegram) when they feel like it, it is not meant to be a complex chat and doesn't handle things well when there are a lot of messages, changing that is, sadly, to much work for us
- We don't want to be a captive app, there're already quite a lot of awesome groups on Telegram and we don't feel like adding other groups, especially on our own platform, would make things better for the community.

But there's clearly a need for people in the same group to get in touch, so what we have in mind to handle this issue is to let people link their own Telegram groups in the Howlr groups (like having a "Link my Telegram Group" option for every group). This solve most of the issue listed above: moderation is done by the group owners, it doesn't use the Howlr chat, and Howlr will just be an entry point among others.

We should have some rule though, like:
- only the owner or administrators of the groups should be able to link it (or unlink)
- the group should have at least a few users already talking on it
- the group should be open

That would probably require having another bot to ensure the group request meet the requirements. No ETA for this for now. In any case, thanks for your suggestion! I let the issue open for now.

**Comment by howlrapp** [comment]
Closing this ticket since there is no plan to maintain this application much further.

Thanks for your suggestion and have a great day!
