### ISSUE TITLE
Unexpected error on iPhone

### ISSUE THREAD

**Issue by agut93** [howlrapp/howlr-app#45]
Hello. I started to use the app at the morning and after 2-3 hours "Unexpected error" is strated to occuring constantly in messages (when I try to click "message" in any profile or open existing chat) and when i try to click "Like". Please help.

**Comment by eSohae** [comment]
Hello,
I'm also experiencing the issue.
Whenever I do anything I get the "unexpected error" message and nothing happens. 

I tried to delete cache and resintall the app, nothing worked.
(Android here)

**Comment by howlrapp** [comment]
Hello!

Let me tell you the story of someone who - this morning - pushed a very simple change in the code (a "- 1" somewhere, just not in the right place), and deployed it without running the tests because they were in a hurry, then proceeded to do a 8 hours walk outside (with the notifications turned off) because the weather was great.

This person was me and I'm really sorry, it should be fixed now. Thanks for you reports!
