### ISSUE TITLE
Bug: Android - Keyboard will overlap the Textfield in Chat view

### ISSUE THREAD

**Issue by Rauca** [howlrapp/howlr-app#50]
Im Chat wird bei einer Eingabe der Text von der Tastatur verdeckt.

**Comment by tymik** [comment]
Can you write your issue in English? This is a lack of respect for the developers to not use English.

**Comment by Rauca** [comment]
In the Chatview the Keyboard will overlap the written Text

**Comment by Rauca** [comment]
A fix is to add 
'keyboardVerticalOffset={Platform.OS === "android" ? 64 : 0}'
in Chat.js after line 95 where the behavior is set (in ContainerCompoent).

**Comment by howlrapp** [comment]
Hello there! Sorry for the late reply, and no worries, this is very well known bug and we are working on it. Sadly as far as I know the behavior of the KeyboardAvoidingView component is quite inconsistent on Android and fixing it is more complicated than settting keyboardVerticalOffset to some values. In the short term we implemented a "modal" mode for the chat and we are going to make it the default for Android until we can work on a better solution.

I'm really sorry because we realise it can be a major inconvenience, have a great day :3

**Comment by floriegl** [comment]
I have checked out https://stackoverflow.com/a/48860983 . From what I have seen in the chat implementation and what I read about windowSoftInputMode it should fix the problem. If I had any real experience with android development I would have checked myself because it looks like this is still the biggest pain point in the app for most users.

**Comment by howlrapp** [comment]
Closing this ticket since there is no plan to maintain this application much further.

Thanks for your suggestion and have a great day!
