### ISSUE TITLE
Any plans for non-telegram login?

### ISSUE THREAD

**Issue by fluffy-critter** [howlrapp/howlr-app#55]
I must be the only member of the fandom to not be on telegram, but it'd be nice if there were alternate login methods, e.g. various common OAuth providers (twitter, github, etc.) or email or something. Is there a particular app design aspect which makes this require Telegram as the one and only identity provider?

Or, if there is a technical reason for it being Telegram-only, could that maybe be explained on the website and app store listings and so on?

**Comment by howlrapp** [comment]
Closing this ticket since there is no plan to maintain this application much further.

To answer your question though: Telegram was just easier for us to implement (especially in the first days for Expo) and seemed to be fine for 99% of our users. Also Telegram takes care or a few things for us like checking for phone numbers uniqueness and things like that.

In any case, thanks for your suggestion and have a great day!
